### PR TITLE
Configure Sidekiq->SSL->Redis

### PR DESCRIPTION
**Pull request by xuanxu**
This PR should fix the error caused by the update of the Heroku SSL certificate.

https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-from-sidekiq

### CODE REVIEW

**Review by mpadge — APPROVED** [review]
Great, thanks so much!

**Comment by mpadge** [comment]
@xuanxu That didn't fix it, unfortunately. It still errors, but now somewhat more specifically. The service errors when starting up because of this:
image
Then after all the lines starting `redis-client`, `connection_pool`, and `sidekiq`, it ends with:
image
It eventually starts, but then actual requests for external services trigger this:
image
... and so ultimately fail

**Comment by xuanxu** [comment]
@mpadge that's weird, are you sure the last commit was deployed?

**Comment by mpadge** [comment]
Yep: 
image

**Comment by xuanxu** [comment]
That looks like a previous deployment from when I merged main into ropensci, last commit should be `b4df1679`

**Comment by mpadge** [comment]
Aha. @maelle and I couldn't figure out yesterday how to trigger a deployment from the web interface. Any tips there?

**Comment by xuanxu** [comment]
In the "Deploy" tab should be a section for "Manual deploys" at the bottom of the page. Just enter the name of the branch (in this case 'ropensci') and click the "Deploy branch" button.

**Comment by mpadge** [comment]
Yeah, that's what we tried, but just get "Item could not be created: Unauthorized". I think "ropensci" is just the name of the GitHub branch, but it's something else on Heroku?

**Comment by xuanxu** [comment]
No, there is nothing else, the name of the GitHub branch is enough. I have deployed that way sometimes without problems.

I guess you don't have permissions to deploy. The owner have to add you as collaborator. You can see who the owner is in the "Access" tab. 
In any case I could do the deployment this evening from my home laptop.

**Comment by mpadge** [comment]
I found out why - the app was connected to GitHub via @maelle's GitHub login, so only she can deploy. Seems there's no way to allow multiple people to deploy that way. And that means we'll have to just wait until auto-deploy tomorrow. If you hear nothing further from me here, it means that everything is working again. Thanks for your help!

**Comment by xuanxu** [comment]
ropensci branch deployed! 🚀

**Comment by mpadge** [comment]
And it works again! Thanks! and ping @maelle with the good news

**Pull request merged**
