### PR TITLE
Fix link to reviewer guide

### PR DESCRIPTION
**Pull request by maelle**
Fix #88 

thx @jemus42

### CODE REVIEW

**Comment by maelle** [comment]
Fixed by #88

**Comment by maelle** [comment]
tests are failing :raised_eyebrow:

**Review by xuanxu — APPROVED** [review]
There was a test checking the link that was sent. I've updated it now so all tests should pass.

**Review by mpadge — APPROVED** [review]

**Comment by maelle** [comment]
Thank you!!

**Pull request merged**
