### PR TITLE
Mint responder

### LINKED ISSUE #26: Responder to change template variable
@xuanxu The [multiple approve commands](https://github.com/ropensci-org/buffy/issues/20) mean that we've got a new `"statsgrade"` variable in one of our templates. Would it be possible to add a responder which could change the value of that variable?

### PR DESCRIPTION
**Pull request by xuanxu**
New MintResponder to grade stats submissions. 
This PR is issued against the `approve-responder`, so ideally should be merged before the PR #27, but it can also be merged later changing the base PR branch to `ropensci`.
Closes #26 

Screenshot of the docs:
docs

### CODE REVIEW

**Comment by mpadge** [comment]
This looks great! I don't see any issues here, nor does it conflict with my comment about #27. Great stuff!

**Comment by maelle** [comment]
@xuanxu now that @mpadge has had a look, I think it can be merged, right? Thank you!

**Comment by xuanxu** [comment]
@maelle yes, this is merge-ready

**Comment by mpadge** [comment]
> @maelle yes, this is merge-ready

@xuanxu I'm not quite sure, because `approve_responder.rb` has this:

``` rb
     if ["bronze", "silver", "gold"].include?(statsgrade)
          labels_to_add << "6/approved-#{statsgrade}"
```

but those `labels_to_add` need to be extracted from the [external service](https://github.com/ropensci-review-tools/roreviewapi/issues/9), right? So they are like `"6/approved-silver-v0.0.1"`.

**Comment by xuanxu** [comment]
@mpadge This PR is ready to merge, it just adds the badge grade value to the body of the issue. So minting will work.
What won't work is the actual labeling when approving the package (the code in the other PR), because the ApproveResponder is not (yet) calling the external service. Nothing to do on your part, I've tested the external service and it is working as expected, so the only missing piece is just adding the call to the ApproveResponder. I'll try to have it ready as ASAP.

**Pull request merged**
